name: CI

on:
  # Triggers the workflow on push or pull request events
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      llvm_version:
        description: "LLVM version"
        default: "20"

jobs:
  build:
    name: Build and Release
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: ./.github/workflows/build-reusable.yml
    with:
      build_ref: ${{ github.sha }}
      release_tag: autobuild-${{ github.sha }}
      is_prerelease: false
      llvm_version: ${{ inputs.llvm_version || '20' }}
